global_frame: /odom
robot_base_frame: /base_link

plugins:
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflated, type: "costmap_2d::InflationLayer"}

update_frequency: 10.0
publish_frequency: 5.0
static_map: false
rolling_window: true
width: 20.0
height: 20.0
resolution: 0.025
origin_x: -10.0
origin_y: -10.0
origin_z: 0.0

transform_tolerance: 0.1
footprint: [[-0.29, 0.19], [-0.29, -0.19], [0.35, -0.19], [0.35, 0.19]]
footprint_padding: 0.03

obstacles:
  observation_sources: scan
  scan: {topic: /scan, data_type: LaserScan, expected_update_rate: 0.15, obstacle_range: 4.5, raytrace_range: 6.7, observation_persistence: 0, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 1.0, inf_is_valid: true}
  track_unknown_space: true
  global_frame: /odom
  robot_base_frame: /base_link

inflated:
  inflation_radius: 0.40
  cost_scaling_factor: 50.0
