global_frame: /map
robot_base_frame: /base_link
update_frequency: 5.0
static_map: true
origin_x: -10.0
origin_y: -10.0
origin_z: 0.0
width: 20.0
height: 20.0


transform_tolerance: 0.1
footprint: [[-0.29, 0.19], [-0.29, -0.19], [0.35, -0.19], [0.35, 0.19]]
footprint_padding: 0.03

plugins:  
  - {name: staticmap, type: "costmap_2d::StaticLayer"}
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}

obstacles:
  observation_sources: scan
  scan: {topic: /scan, data_type: LaserScan, expected_update_rate: 0.15, obstacle_range: 4.5, raytrace_range: 6.7, observation_persistence: 0, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 1.0, inf_is_valid: true}
  track_unknown_space: true
  global_frame: /map
  robot_base_frame: /base_link
